#!/usr/bin/env python3
"""Build the inline flag sprite at src/assets/flags.ts.

Run only when the flag set changes:

    npm pack country-flag-icons@1.6.20 && tar xzf country-flag-icons-1.6.20.tgz
    python scripts/build-flags.py package/3x2 src/assets/flags.ts

Why this source and not flag-icons: flag-icons draws every coat of arms by hand
(Spain 91 KB, Serbia 184 KB, 1.1 MB for a set of 120). At the 20x13 px the card
actually shows, those paths are sub-pixel. country-flag-icons rounds its
coordinates and drops what cannot be seen -- the same flag is 599 bytes.

**Every ISO 3166-1 alpha-2 flag the source ships is included, not a curated
subset.** The hub looks a node's country up from an IP and stores it as "ISO
3166-1 alpha-2, uppercase" (see monitor's db.rs), so any code can arrive. A code
with no artwork does not break -- Flag() falls back to a plain two-letter badge
-- which is exactly why the previous hand-written list of 120 could rot in
silence: CN, GB and ~130 other countries shipped with no flag for two releases.

Flag artwork: country-flag-icons (MIT)
https://github.com/UNITED-ELECTRONICS/country-flag-icons
"""
import gzip
import json
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "package/3x2"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/assets/flags.ts"

# The source directory is the authority on which flags exist, not a list written
# here: the hand-written one this replaced named 120 codes and had no artwork for
# CN or GB, and nothing failed -- a missing flag is a plain badge, not an error.
#
# Four are held back deliberately:
#   TW        -- 中国台湾 has no regional flag; it keeps the plain code badge.
#   XA XC XO  -- country-flag-icons' placeholder artwork. Not country codes, and
#                no lookup can return them.
# The subdivisions the source also ships (GB-ENG, GB-SCT, ES-CT, BQ-SA, ...) fall
# out of the two-letter filter: the hub's country is always exactly two letters.
EXCLUDE = {"TW", "XA", "XC", "XO"}
if not os.path.isdir(SRC):
    sys.exit(f"{SRC} is not a directory -- unpack country-flag-icons first (see the docstring)")
CODES = sorted(
    name[:-4]
    for name in os.listdir(SRC)
    if name.endswith(".svg") and re.fullmatch(r"[A-Z]{2}", name[:-4]) and name[:-4] not in EXCLUDE
)
# A partial run used to be indistinguishable from a small one. 265 SVGs ship 257
# two-letter codes; anything near that is the real set, and anything far below it
# is a wrong or half-unpacked directory.
if len(CODES) < 200:
    sys.exit(f"{SRC} holds only {len(CODES)} two-letter flags; refusing to write a partial sprite")


def read(code):
    with open(os.path.join(SRC, code + ".svg"), encoding="utf-8") as fh:
        return fh.read()


def body_of(svg):
    body = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
    return re.sub(r"</svg>\s*$", "", body, flags=re.S).strip()


def viewbox_of(svg):
    match = re.search(r'viewBox="([^"]+)"', svg)
    return match.group(1) if match else "0 0 640 480"


def namespace(body, code):
    """One document holds every flag, so no id may repeat. Several flags name a
    clip path or mask simply "a"; prefix anything not already unique."""
    for old in sorted(set(re.findall(r'\bid="([^"]+)"', body))):
        if old.startswith(code + "-"):
            continue
        new = f"{code}-{old}"
        body = re.sub(rf'\bid="{re.escape(old)}"', f'id="{new}"', body)
        body = body.replace(f'href="#{old}"', f'href="#{new}"')
        body = body.replace(f"url(#{old})", f"url(#{new})")
    return body


symbols, views = [], {}
for code in CODES:
    # Existence is guaranteed by the discovery above, so a FileNotFoundError here
    # is a concurrent change to the source and should be loud rather than skipped.
    svg = read(code)
    views.setdefault(viewbox_of(svg), []).append(code)
    body = re.sub(r">\s+<", "><", namespace(body_of(svg), code))
    symbols.append(f'<symbol id="flag-{code.lower()}" viewBox="{viewbox_of(svg)}">{body}</symbol>')

sprite = "".join(symbols)
known = CODES
print(f"flags   : {len(symbols)}")
print(f"viewBox : {', '.join(f'{view} x{len(c)}' for view, c in views.items())}")
print(f"raw     : {len(sprite)} bytes")
print(f"gzipped : {len(gzip.compress(sprite.encode()))} bytes")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(
        "// GENERATED by scripts/build-flags.py -- do not edit by hand.\n"
        "//\n"
        "// Flag artwork: country-flag-icons (MIT),\n"
        "// https://github.com/UNITED-ELECTRONICS/country-flag-icons\n"
        "//\n"
        "// One string rather than a hundred <path> literals: the sprite is a single\n"
        "// text node, which gzips far better than the equivalent markup and parses\n"
        "// in one pass. Inlined rather than fetched because a sprite in the bundle\n"
        "// cannot 404, needs no MIME type from the hub, and costs no request.\n"
        "\n"
        "/** Codes with artwork here; anything else keeps the plain text badge. */\n"
        f'export const FLAG_CODES = new Set("{",".join(known)}".split(","))\n'
        "\n"
        f"export const FLAG_SPRITE = {json.dumps(sprite)}\n"
    )
print(f"wrote   : {OUT}")
