#!/usr/bin/env python3
"""Build the inline flag sprite at src/assets/flags.ts.

Run only when the flag set changes:

    npm pack country-flag-icons@1.6.20 && tar xzf country-flag-icons-1.6.20.tgz
    python scripts/build-flags.py package/3x2 src/assets/flags.ts

Why this source and not flag-icons: flag-icons draws every coat of arms by hand
(Spain 91 KB, Serbia 184 KB, 1.1 MB for a set of 120). At the 20x13 px the card
actually shows, those paths are sub-pixel. country-flag-icons rounds its
coordinates and drops what cannot be seen -- the same flag is 599 bytes, and the
whole 120-flag sprite is 71 KB, 21 KB gzipped.

Flag artwork: country-flag-icons (MIT)
https://github.com/UNITED-ELECTRONICS/country-flag-icons
"""
import gzip
import json
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "package/3x2"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/assets/flags.ts"

# Places a node can actually sit. Not the full ISO list -- the long tail would
# only pad the bundle. `TW` is deliberately absent: 中国台湾 has no regional flag,
# so it keeps the plain code badge, as does anything else not listed here.
CODES = """
AE AL AM AR AT AU AZ BA BE BG BH BN BO BR BY CA CH CL CM CO CR CY CZ DE DK DO
DZ EC EE EG ES ET FI FJ FR GE GH GR GT HK HN HR HU ID IE IL IM IN IQ IR IS IT
JE JO JP KE KG KH KR KW KZ LA LB LK LT LU LV LY MA MD ME MK MM MN MO MT MU MV
MX MY NG NI NL NO NP NZ OM PA PE PH PK PL PR PS PT PY QA RO RS RU SA SE SG SI
SK SN SV TH TN TR UA UG US UY UZ VE VN ZA ZM ZW
""".split()


def read(code):
    with open(os.path.join(SRC, code + ".svg"), encoding="utf-8") as fh:
        return fh.read()


def body_of(svg):
    body = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
    return re.sub(r"</svg>\s*$", "", body, flags=re.S).strip()


def viewbox_of(svg):
    match = re.search(r'viewBox="([^"]+)"', svg)
    return match.group(1) if match else "0 0 640 480"


def namespace(body, code):
    """One document holds every flag, so no id may repeat. Several flags name a
    clip path or mask simply "a"; prefix anything not already unique."""
    for old in sorted(set(re.findall(r'\bid="([^"]+)"', body))):
        if old.startswith(code + "-"):
            continue
        new = f"{code}-{old}"
        body = re.sub(rf'\bid="{re.escape(old)}"', f'id="{new}"', body)
        body = body.replace(f'href="#{old}"', f'href="#{new}"')
        body = body.replace(f"url(#{old})", f"url(#{new})")
    return body


symbols, missing, views = [], [], {}
for code in CODES:
    try:
        svg = read(code)
    except FileNotFoundError:
        missing.append(code)
        continue
    views.setdefault(viewbox_of(svg), []).append(code)
    body = re.sub(r">\s+<", "><", namespace(body_of(svg), code))
    symbols.append(f'<symbol id="flag-{code.lower()}" viewBox="{viewbox_of(svg)}">{body}</symbol>')

sprite = "".join(symbols)
known = [code for code in CODES if code not in missing]
print(f"flags   : {len(symbols)}  (missing: {missing or 'none'})")
print(f"viewBox : {', '.join(f'{view} x{len(c)}' for view, c in views.items())}")
print(f"raw     : {len(sprite)} bytes")
print(f"gzipped : {len(gzip.compress(sprite.encode()))} bytes")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(
        "// GENERATED by scripts/build-flags.py -- do not edit by hand.\n"
        "//\n"
        "// Flag artwork: country-flag-icons (MIT),\n"
        "// https://github.com/UNITED-ELECTRONICS/country-flag-icons\n"
        "//\n"
        "// One string rather than a hundred <path> literals: the sprite is a single\n"
        "// text node, which gzips far better than the equivalent markup and parses\n"
        "// in one pass. Inlined rather than fetched because a sprite in the bundle\n"
        "// cannot 404, needs no MIME type from the hub, and costs no request.\n"
        "\n"
        "/** Codes with artwork here; anything else keeps the plain text badge. */\n"
        f'export const FLAG_CODES = new Set("{",".join(known)}".split(","))\n'
        "\n"
        f"export const FLAG_SPRITE = {json.dumps(sprite)}\n"
    )
print(f"wrote   : {OUT}")
